# Generated by Django 6.1 on 2026-09-03 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('palestra', 'Palestra'), ('workshop', 'Workshop'), ('curso', 'Curso'), ('seminario', 'Seminário'), ('congresso', 'Congresso'), ('feira', 'Feira Acadêmica'), ('outro', 'Outro')], default='palestra', max_length=20),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='eventos.evento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estudante', 'evento'), name='favorito_unico_por_evento')],
            },
        ),
    ]
