# Generated by Django 6.1 on 2026-09-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_categoria_favorito'),
        ('planos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorito',
            name='favorito_unico_por_evento',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='estudante',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='planos.plano', verbose_name='Plano do evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='carga_horaria',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('palestra', 'Palestra'), ('workshop', 'Workshop'), ('curso', 'Curso'), ('seminario', 'Seminário'), ('congresso', 'Congresso'), ('feira', 'Feira'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'evento'), name='favorito_unico_por_evento'),
        ),
    ]
