# Generated by Django 6.1 on 2026-09-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_favorito_favorito_unico_por_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='logo_certificado',
            field=models.ImageField(blank=True, help_text='Logo da empresa, instituição ou organizador que será exibida no certificado.', null=True, upload_to='logos_certificados/', verbose_name='Logo para o certificado'),
        ),
    ]
