# Generated by Django 6.1 on 2026-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('espera', 'Lista de espera'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20),
        ),
    ]
