# Generated by Django 6.1 on 2026-09-02 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('presenca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='presencas.presenca')),
            ],
        ),
    ]
