# Generated by Django 6.1 on 2026-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='assinatura_solana',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='data_registro_solana',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='hash_certificado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='rede_solana',
            field=models.CharField(default='devnet', max_length=20),
        ),
        migrations.AddField(
            model_name='certificado',
            name='registrado_solana',
            field=models.BooleanField(default=False),
        ),
    ]
