# Generated by Django 6.1 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instituicao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
