# Generated by Django 6.1 on 2026-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_curso_usuario_instituicao_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carteira_solana',
            field=models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Carteira Solana'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carteira_solana_verificada',
            field=models.BooleanField(default=False, verbose_name='Carteira Solana verificada'),
        ),
    ]
