"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / '.env')


DEBUG = os.getenv(
    'DEBUG',
    'False'
).lower() == 'true'


RAILWAY_PUBLIC_DOMAIN = os.getenv(
    'RAILWAY_PUBLIC_DOMAIN'
)


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


CSRF_TRUSTED_ORIGINS = []


if RAILWAY_PUBLIC_DOMAIN:

    ALLOWED_HOSTS.append(
        RAILWAY_PUBLIC_DOMAIN
    )

    CSRF_TRUSTED_ORIGINS.append(
        f'https://{RAILWAY_PUBLIC_DOMAIN}'
    )

SECRET_KEY = os.getenv('SECRET_KEY')

# Chave somente para desenvolvimento/testes locais
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-acadevents-local-development-only'
    else:
        raise RuntimeError(
            'SECRET_KEY não encontrada no arquivo .env.'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Apps do AcadEvents

    'eventos',
    'core',
    'inscricoes.apps.InscricoesConfig',
    'presencas.apps.PresencasConfig',
    'certificados',
    'usuarios',
    'notificacoes.apps.NotificacoesConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notificacoes.context_processors.notificacoes_nao_lidas',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.getenv(
            'PGDATABASE',
            os.getenv('DB_NAME')
        ),

        'USER': os.getenv(
            'PGUSER',
            os.getenv('DB_USER')
        ),

        'PASSWORD': os.getenv(
            'PGPASSWORD',
            os.getenv('DB_PASSWORD')
        ),

        'HOST': os.getenv(
            'PGHOST',
            os.getenv('DB_HOST', 'localhost')
        ),

        'PORT': os.getenv(
            'PGPORT',
            os.getenv('DB_PORT', '5432')
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'usuarios.Usuario'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        'OPTIONS': {},
    },
}

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/usuarios/login/'

DEFAULT_FROM_EMAIL = 'AcadEvents <noreply@acadevents.com>'
