# Generated by Django 6.1 on 2026-09-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('free', 'Free'), ('avulso', 'Evento avulso'), ('assinatura', 'Assinatura'), ('institucional', 'Institucional')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_participantes', models.PositiveIntegerField(blank=True, help_text='Deixe vazio para ilimitado.', null=True)),
                ('limite_eventos_mes', models.PositiveIntegerField(blank=True, help_text='Usado principalmente em assinaturas.', null=True)),
                ('permite_inscricoes', models.BooleanField(default=False)),
                ('permite_eventos_pagos', models.BooleanField(default=False)),
                ('permite_qr_code', models.BooleanField(default=False)),
                ('permite_presenca', models.BooleanField(default=False)),
                ('permite_certificados', models.BooleanField(default=False)),
                ('permite_relatorios', models.BooleanField(default=False)),
                ('permite_solana', models.BooleanField(default=False)),
                ('permite_logo_certificado', models.BooleanField(default=False)),
                ('prioridade_divulgacao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['preco'],
            },
        ),
        migrations.CreateModel(
            name='ContratacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_contratados', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='planos.plano')),
            ],
        ),
    ]
