# Generated by Django 6.1 on 2026-09-02 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca', to='inscricoes.inscricao')),
            ],
        ),
    ]
